[project]
name = "streamlit-app"
requires-python = ">=3.11"
version = "0.0.1"
description = ""
dependencies = [
    "streamlit"
]

[tool.snowflake]
# Aquí le decimos explícitamente a Snowflake que use su canal interno de Anaconda
# para cargar estos paquetes sin intentar salir a internet.
dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "matplotlib",
    "scikit-learn",
    "scipy",
    "pulp",
    "reportlab",
    "pypdf"
]

[tool.uv]
constraint-dependencies = ["numba>=0.56.0"]