[project]
name = "gla-streamlit"
version = "0.1.0"
description = "GLA Streamlit App"
requires-python = ">=3.11"

dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "plotly",
    "pulp",
    "python-dotenv",
    "scikit-learn",
    "scipy",
    "snowflake-connector-python",
    "snowflake-snowpark-python",
    "streamlit",
    "reportlab",
    "pypdf"
]