[project]
name = "streamlit-app"
requires-python = "~=3.11.0"
version = "0.0.1"
description = ""
dependencies = [
    "streamlit"
]

[tool.snowflake]
# Obligamos al motor a jalar todas estas librerías desde el entorno seguro local de Snowflake
dependencies = [
    "numpy",
    "pandas",
    "plotly",
    "matplotlib",
    "scikit-learn",
    "scipy",
    "pulp",
    "reportlab",
    "pypdf"
]

[tool.uv]
constraint-dependencies = ["numba>=0.56.0"]